# Generated by Django 2.2.6 on 2020-01-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shipment_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PONumber', models.CharField(max_length=200)),
                ('SupNam', models.CharField(max_length=200)),
                ('SupAddress', models.CharField(max_length=200)),
                ('Composition', models.CharField(max_length=200)),
                ('ClothingStructure', models.CharField(max_length=200)),
                ('MerchandiseDescription', models.CharField(max_length=200)),
                ('PaymentCondition', models.CharField(max_length=200)),
                ('TransportationMethod', models.CharField(max_length=200)),
                ('DeliveryCondition', models.CharField(max_length=200)),
                ('GrossWeight', models.FloatField()),
                ('NetWeight', models.FloatField()),
                ('GwNwRatio', models.FloatField()),
                ('carton', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('UnitPrice', models.FloatField()),
                ('currency', models.FloatField()),
                ('TotalAmount', models.FloatField()),
                ('PackOrSet', models.CharField(max_length=200)),
                ('UnitPriceBreakdown', models.FloatField()),
                ('pig', models.IntegerField()),
                ('CoO', models.CharField(max_length=200)),
                ('PackingMethod', models.CharField(max_length=200)),
                ('HSCode', models.CharField(max_length=200)),
            ],
        ),
    ]
