# Generated by Django 2.2.6 on 2020-01-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20200112_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment_details',
            name='USIMno',
            field=models.IntegerField(default=0),
        ),
    ]
