# Generated by Django 2.2.6 on 2020-01-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_shipment_details_usimno'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplier_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SuppCode', models.IntegerField(max_length=5)),
                ('SupplierName', models.CharField(max_length=200)),
                ('RexNo', models.CharField(max_length=10)),
                ('SupplierAddress', models.CharField(max_length=200)),
            ],
        ),
    ]
