# Generated by Django 2.2.6 on 2020-01-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_supplier_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment_details',
            name='isReviewed',
            field=models.BooleanField(default=False),
        ),
    ]
